begin;
revoke all on function public.takt_is_member(uuid) from public;
revoke all on function public.takt_can_access_message(uuid) from public;
revoke all on function public.takt_are_blocked(uuid) from public;
revoke all on function public.takt_handle_new_user() from public;
revoke all on function public.takt_touch_updated_at() from public;
revoke all on function public.takt_require_user_id() from public;
revoke all on function public.takt_message_json(uuid) from public;
revoke all on function public.takt_conversation_json(uuid) from public;
revoke all on function public.takt_list_conversations() from public;
revoke all on function public.takt_bootstrap() from public;
revoke all on function public.takt_get_conversation(uuid) from public;
revoke all on function public.takt_update_profile(text, text, text, text) from public;
revoke all on function public.takt_search_people(text) from public;
revoke all on function public.takt_open_direct_chat(uuid) from public;
revoke all on function public.takt_create_group(text, uuid[], text) from public;
revoke all on function public.takt_send_message(uuid, text, uuid, uuid) from public;
revoke all on function public.takt_send_attachment(uuid, text, text, text, public.takt_message_kind, integer, text) from public;
revoke all on function public.takt_get_attachment(uuid) from public;
revoke all on function public.takt_edit_message(uuid, text) from public;
revoke all on function public.takt_delete_message(uuid, boolean) from public;
revoke all on function public.takt_toggle_reaction(uuid, text) from public;
revoke all on function public.takt_mark_read(uuid) from public;
revoke all on function public.takt_update_chat_settings(uuid, boolean, boolean, uuid, timestamptz, text) from public;
revoke all on function public.takt_create_folder(text, text) from public;
revoke all on function public.takt_set_typing(uuid, text) from public;
revoke all on function public.takt_set_presence(boolean) from public;
revoke all on function public.takt_toggle_block(uuid, boolean) from public;
revoke all on function public.takt_submit_report(uuid, uuid, text) from public;
revoke all on function public.takt_search_messages(text, uuid) from public;
revoke all on function public.takt_start_call(uuid, boolean) from public;
revoke all on function public.takt_end_call(uuid) from public;
revoke all on function public.takt_call_token_context(uuid) from public;
revoke all on function public.takt_update_privacy(text, text, text, text) from public;
grant execute on function public.takt_is_member(uuid) to authenticated;
grant execute on function public.takt_can_access_message(uuid) to authenticated;
grant execute on function public.takt_are_blocked(uuid) to authenticated;
grant execute on function public.takt_require_user_id() to authenticated;
grant execute on function public.takt_message_json(uuid) to authenticated;
grant execute on function public.takt_conversation_json(uuid) to authenticated;
grant execute on function public.takt_list_conversations() to authenticated;
grant execute on function public.takt_bootstrap() to authenticated;
grant execute on function public.takt_get_conversation(uuid) to authenticated;
grant execute on function public.takt_update_profile(text, text, text, text) to authenticated;
grant execute on function public.takt_search_people(text) to authenticated;
grant execute on function public.takt_open_direct_chat(uuid) to authenticated;
grant execute on function public.takt_create_group(text, uuid[], text) to authenticated;
grant execute on function public.takt_send_message(uuid, text, uuid, uuid) to authenticated;
grant execute on function public.takt_send_attachment(uuid, text, text, text, public.takt_message_kind, integer, text) to authenticated;
grant execute on function public.takt_get_attachment(uuid) to authenticated;
grant execute on function public.takt_edit_message(uuid, text) to authenticated;
grant execute on function public.takt_delete_message(uuid, boolean) to authenticated;
grant execute on function public.takt_toggle_reaction(uuid, text) to authenticated;
grant execute on function public.takt_mark_read(uuid) to authenticated;
grant execute on function public.takt_update_chat_settings(uuid, boolean, boolean, uuid, timestamptz, text) to authenticated;
grant execute on function public.takt_create_folder(text, text) to authenticated;
grant execute on function public.takt_set_typing(uuid, text) to authenticated;
grant execute on function public.takt_set_presence(boolean) to authenticated;
grant execute on function public.takt_toggle_block(uuid, boolean) to authenticated;
grant execute on function public.takt_submit_report(uuid, uuid, text) to authenticated;
grant execute on function public.takt_search_messages(text, uuid) to authenticated;
grant execute on function public.takt_start_call(uuid, boolean) to authenticated;
grant execute on function public.takt_end_call(uuid) to authenticated;
grant execute on function public.takt_call_token_context(uuid) to authenticated;
grant execute on function public.takt_update_privacy(text, text, text, text) to authenticated;

commit;

